import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Getting Started","description":"","frontmatter":{},"headers":[],"relativePath":"getting-started.md","filePath":"getting-started.md"}');
const _sfc_main = { name: "getting-started.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="getting-started" tabindex="-1">Getting Started <a class="header-anchor" href="#getting-started" aria-label="Permalink to &quot;Getting Started&quot;">​</a></h1><p>This guide walks you through creating your first documentation with Eddie.</p><h2 id="directory-structure" tabindex="-1">Directory Structure <a class="header-anchor" href="#directory-structure" aria-label="Permalink to &quot;Directory Structure&quot;">​</a></h2><p>After running <code>npx create-eddie my-docs</code>, you&#39;ll see:</p><div class="language-"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span>my-docs/</span></span>
<span class="line"><span>├── edit/                   # User-facing workspace</span></span>
<span class="line"><span>│   ├── 0.prompt🤖/         # AI prompt templates</span></span>
<span class="line"><span>│   ├── 1.source📦/         # Raw materials</span></span>
<span class="line"><span>│   ├── 2.sampling✂️/       # Extracted content</span></span>
<span class="line"><span>│   ├── 3.plot📋/           # Document outlines</span></span>
<span class="line"><span>│   ├── 4.publish📚/        # Final docs (becomes website)</span></span>
<span class="line"><span>│   └── archive🗑️/          # Unused materials</span></span>
<span class="line"><span>├── .system/                # Backend (don&#39;t touch)</span></span>
<span class="line"><span>│   ├── site-config/        # VitePress config</span></span>
<span class="line"><span>│   ├── claude/             # Claude Code settings</span></span>
<span class="line"><span>│   └── vector-data/        # Search index</span></span>
<span class="line"><span>├── .env                    # OpenAI API key</span></span>
<span class="line"><span>└── README.md</span></span></code></pre></div><h2 id="the-eddie-workflow" tabindex="-1">The Eddie Workflow <a class="header-anchor" href="#the-eddie-workflow" aria-label="Permalink to &quot;The Eddie Workflow&quot;">​</a></h2><p>Eddie follows a 5-stage process inspired by professional writing:</p><h3 id="stage-0-prompt-🤖" tabindex="-1">Stage 0: Prompt 🤖 <a class="header-anchor" href="#stage-0-prompt-🤖" aria-label="Permalink to &quot;Stage 0: Prompt 🤖&quot;">​</a></h3><p>Create AI prompts to generate content ideas.</p><p><strong>Example</strong>: <code>edit/0.prompt🤖/interview-prompt.md</code></p><div class="language-markdown"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">Interview a developer about their favorite framework.</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">Ask about:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- Why they chose it</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- What problems it solves</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- Best practices</span></span></code></pre></div><h3 id="stage-1-source-📦" tabindex="-1">Stage 1: Source 📦 <a class="header-anchor" href="#stage-1-source-📦" aria-label="Permalink to &quot;Stage 1: Source 📦&quot;">​</a></h3><p>Store raw materials like transcripts, notes, or research.</p><p><strong>Example</strong>: <code>edit/1.source📦/interview-transcript.md</code></p><div class="language-markdown"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">Q: Why did you choose Next.js?</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">A: It solved our SSR and routing problems...</span></span></code></pre></div><h3 id="stage-2-sampling-✂️" tabindex="-1">Stage 2: Sampling ✂️ <a class="header-anchor" href="#stage-2-sampling-✂️" aria-label="Permalink to &quot;Stage 2: Sampling ✂️&quot;">​</a></h3><p>Extract and refine key points from source materials.</p><p><strong>Example</strong>: <code>edit/2.sampling✂️/nextjs-benefits.md</code></p><div class="language-markdown"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}">## Next.js Benefits</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- Built-in SSR</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- File-based routing</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- API routes</span></span></code></pre></div><h3 id="stage-3-plot-📋" tabindex="-1">Stage 3: Plot 📋 <a class="header-anchor" href="#stage-3-plot-📋" aria-label="Permalink to &quot;Stage 3: Plot 📋&quot;">​</a></h3><p>Create outlines for your final documents.</p><p><strong>Example</strong>: <code>edit/3.plot📋/nextjs-guide-outline.md</code></p><div class="language-markdown"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}"># Next.js Guide Outline</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">1. Introduction</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">2. Key Features</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">3. Getting Started</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">4. Best Practices</span></span></code></pre></div><h3 id="stage-4-publish-📚" tabindex="-1">Stage 4: Publish 📚 <a class="header-anchor" href="#stage-4-publish-📚" aria-label="Permalink to &quot;Stage 4: Publish 📚&quot;">​</a></h3><p>Write final, polished documentation. <strong>This becomes your website.</strong></p><p><strong>Example</strong>: <code>edit/4.publish📚/nextjs-guide.md</code></p><div class="language-markdown"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}"># Next.js Guide</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">Next.js is a React framework that provides...</span></span></code></pre></div><h2 id="your-first-document" tabindex="-1">Your First Document <a class="header-anchor" href="#your-first-document" aria-label="Permalink to &quot;Your First Document&quot;">​</a></h2><p>Let&#39;s create a simple guide:</p><h3 id="_1-create-a-source-file" tabindex="-1">1. Create a Source File <a class="header-anchor" href="#_1-create-a-source-file" aria-label="Permalink to &quot;1. Create a Source File&quot;">​</a></h3><p>Create <code>edit/1.source📦/my-notes.md</code>:</p><div class="language-markdown"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}"># Project Notes</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- Eddie uses VitePress for static sites</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- Vector search uses OpenAI embeddings</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- Obsidian wikilinks work automatically</span></span></code></pre></div><h3 id="_2-extract-key-points" tabindex="-1">2. Extract Key Points <a class="header-anchor" href="#_2-extract-key-points" aria-label="Permalink to &quot;2. Extract Key Points&quot;">​</a></h3><p>Create <code>edit/2.sampling✂️/eddie-features.md</code>:</p><div class="language-markdown"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}">## Eddie Features</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- </span><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}">**VitePress**</span><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">: Static site generation</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- </span><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}">**Vector Search**</span><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">: Semantic document navigation</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- </span><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}">**Obsidian**</span><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">: Wikilink support</span></span></code></pre></div><h3 id="_3-create-outline" tabindex="-1">3. Create Outline <a class="header-anchor" href="#_3-create-outline" aria-label="Permalink to &quot;3. Create Outline&quot;">​</a></h3><p>Create <code>edit/3.plot📋/eddie-overview-outline.md</code>:</p><div class="language-markdown"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}"># Eddie Overview Outline</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">1. What is Eddie?</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">2. Key Features</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">3. Why Use Eddie?</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">4. Next Steps</span></span></code></pre></div><h3 id="_4-write-final-document" tabindex="-1">4. Write Final Document <a class="header-anchor" href="#_4-write-final-document" aria-label="Permalink to &quot;4. Write Final Document&quot;">​</a></h3><p>Create <code>edit/4.publish📚/eddie-overview.md</code>:</p><div class="language-markdown"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}"># Eddie Overview</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">Eddie is an AI-assisted documentation framework...</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}">## Key Features</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- VitePress for static sites</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- Vector search for navigation</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">- Obsidian integration</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1", "font-weight": "bold" })}">## Why Use Eddie?</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">Traditional docs are too rigid or too loose...</span></span></code></pre></div><h3 id="_5-view-your-site" tabindex="-1">5. View Your Site <a class="header-anchor" href="#_5-view-your-site" aria-label="Permalink to &quot;5. View Your Site&quot;">​</a></h3><p>Run the dev server:</p><div class="language-bash"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">npm</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> run</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> dev</span></span></code></pre></div><p>Visit <a href="http://localhost:5173/eddie-overview" target="_blank" rel="noreferrer">http://localhost:5173/eddie-overview</a></p><h2 id="using-vector-search" tabindex="-1">Using Vector Search <a class="header-anchor" href="#using-vector-search" aria-label="Permalink to &quot;Using Vector Search&quot;">​</a></h2><p>Index your documents:</p><div class="language-bash"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">npm</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> run</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> reindex</span></span></code></pre></div><p>Search semantically:</p><div class="language-bash"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">npm</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> run</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> search</span><span style="${ssrRenderStyle({ "color": "#22863A" })}"> &quot;how to create documentation&quot;</span></span></code></pre></div><p>Results show relevant documents even if they don&#39;t contain exact keywords.</p><h2 id="linking-between-documents" tabindex="-1">Linking Between Documents <a class="header-anchor" href="#linking-between-documents" aria-label="Permalink to &quot;Linking Between Documents&quot;">​</a></h2><p>Use Obsidian wikilinks or standard markdown:</p><div class="language-markdown"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">See [[</span><span style="${ssrRenderStyle({ "color": "#D32F2F" })}">installation</span><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">]] for setup.</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#24292EFF" })}">See </span><span style="${ssrRenderStyle({ "color": "#1976D2", "text-decoration": "underline" })}">[</span><span style="${ssrRenderStyle({ "color": "#D32F2F", "text-decoration": "underline" })}">installation</span><span style="${ssrRenderStyle({ "color": "#1976D2", "text-decoration": "underline" })}">]</span><span style="${ssrRenderStyle({ "color": "#22863A", "text-decoration": "underline" })}">(./installation.md)</span><span style="${ssrRenderStyle({ "color": "#24292EFF" })}"> for setup.</span></span></code></pre></div><p>Both work in VitePress!</p><h2 id="using-with-claude-code" tabindex="-1">Using with Claude Code <a class="header-anchor" href="#using-with-claude-code" aria-label="Permalink to &quot;Using with Claude Code&quot;">​</a></h2><ol><li>Open project in VS Code: <code>code .</code></li><li>Launch Claude Code</li><li>Ask for help: <blockquote><p>&quot;Read my notes in 1.source📦 and create an outline in 3.plot📋&quot;</p></blockquote></li></ol><p>Claude can navigate your Eddie structure and help with each stage.</p><h2 id="next-steps" tabindex="-1">Next Steps <a class="header-anchor" href="#next-steps" aria-label="Permalink to &quot;Next Steps&quot;">​</a></h2><ul><li><a href="./workflow.html">Workflow</a> - Deep dive into each stage</li><li><a href="./vector-search.html">Vector Search</a> - Advanced search usage</li><li><a href="./deployment.html">Deployment</a> - Publish to the web</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("getting-started.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const gettingStarted = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  gettingStarted as default
};
