import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Eddie","description":"","frontmatter":{},"headers":[],"relativePath":"index.md","filePath":"index.md"}');
const _sfc_main = { name: "index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="eddie" tabindex="-1">Eddie <a class="header-anchor" href="#eddie" aria-label="Permalink to &quot;Eddie&quot;">​</a></h1><p><strong>AI-Assisted Documentation Framework for Obsidian + Claude Code</strong></p><p>Eddie is a documentation system that combines:</p><ul><li>📝 <strong>Obsidian</strong> - Markdown editor with wikilinks</li><li>🤖 <strong>Claude Code</strong> - AI-powered writing assistant</li><li>🌐 <strong>VitePress</strong> - Static site generator</li><li>🔍 <strong>Vector Search</strong> - Semantic document navigation</li></ul><h2 id="why-eddie" tabindex="-1">Why Eddie? <a class="header-anchor" href="#why-eddie" aria-label="Permalink to &quot;Why Eddie?&quot;">​</a></h2><p>Traditional documentation tools are either too rigid (CMS) or too loose (raw markdown). Eddie gives you:</p><p>✅ <strong>AI-Native Workflow</strong> - Prompt-driven content creation from 0.prompt🤖 to 4.publish📚 ✅ <strong>Obsidian Integration</strong> - Use your favorite markdown editor with wikilinks ✅ <strong>Automatic Deployment</strong> - Push to GitHub → Vercel builds your site ✅ <strong>Semantic Search</strong> - Find documents by meaning, not just keywords</p><h2 id="quick-start" tabindex="-1">Quick Start <a class="header-anchor" href="#quick-start" aria-label="Permalink to &quot;Quick Start&quot;">​</a></h2><div class="language-bash"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">npx</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> create-eddie</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> my-docs</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">cd</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> my-docs</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">cp</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> .env.example</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> .env</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C2C3C5" })}"># Add your OPENAI_API_KEY to .env</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">npm</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> run</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> dev</span></span></code></pre></div><p>Open <a href="http://localhost:5173" target="_blank" rel="noreferrer">http://localhost:5173</a> to see your site.</p><h2 id="documentation" tabindex="-1">Documentation <a class="header-anchor" href="#documentation" aria-label="Permalink to &quot;Documentation&quot;">​</a></h2><ul><li><a href="./installation.html">Installation</a> - Setup and requirements</li><li><a href="./getting-started.html">Getting Started</a> - Your first Eddie project</li><li><a href="./workflow.html">Workflow</a> - The 5-stage documentation process</li><li><a href="./vector-search.html">Vector Search</a> - Semantic search usage</li><li><a href="./deployment.html">Deployment</a> - Deploy to Vercel</li></ul><h2 id="workflow-overview" tabindex="-1">Workflow Overview <a class="header-anchor" href="#workflow-overview" aria-label="Permalink to &quot;Workflow Overview&quot;">​</a></h2><div class="language-"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span>0.prompt🤖   → AI prompt templates</span></span>
<span class="line"><span>1.source📦   → Raw materials (transcripts, notes)</span></span>
<span class="line"><span>2.sampling✂️ → Extract and refine content</span></span>
<span class="line"><span>3.plot📋     → Create document outlines</span></span>
<span class="line"><span>4.publish📚  → Write final docs → Deploy to web</span></span>
<span class="line"><span>archive🗑️    → Archive unused materials</span></span></code></pre></div><h2 id="commands" tabindex="-1">Commands <a class="header-anchor" href="#commands" aria-label="Permalink to &quot;Commands&quot;">​</a></h2><div class="language-bash"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki min-light vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">npm</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> run</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> dev</span><span style="${ssrRenderStyle({ "color": "#C2C3C5" })}">         # Start dev server (http://localhost:5173)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">npm</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> run</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> build</span><span style="${ssrRenderStyle({ "color": "#C2C3C5" })}">       # Build static site</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">npm</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> run</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> preview</span><span style="${ssrRenderStyle({ "color": "#C2C3C5" })}">     # Preview built site</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">npm</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> run</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> search</span><span style="${ssrRenderStyle({ "color": "#22863A" })}"> &quot;query&quot;</span><span style="${ssrRenderStyle({ "color": "#C2C3C5" })}">  # Semantic search</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">npm</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> run</span><span style="${ssrRenderStyle({ "color": "#2B5581" })}"> reindex</span><span style="${ssrRenderStyle({ "color": "#C2C3C5" })}">         # Re-index all documents</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
